### ISSUE TITLE
Report of performing acceptance-tests in test cell

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_robots#446]
### acceptance_test_speed_monitoring
Sometimes moving the robot with RViz fails with error:
```
[ERROR] [1596029290.842323725]: 
Invalid Trajectory: start point deviates from current robot state more than 0.01
joint 'prbt_joint_1': expected: -0.331473, current: -0.347024
```
I guess this can happen if you move the robot without moveit?
See https://github.com/ros-planning/moveit/issues/1939#issuecomment-666191991

### acceptance_test_execute_brake_test
Only fails in test cell, since the braketest module is not present there, yet.

### acceptance_test_stop1

controller is in holding mode at start -> First test fails #456 

### acceptance_test_joint_limits

- controller is in holding mode at start -> First test fails #456 
- could not observe any log output indicating a joint limit violation
- trajectory is always successful, therefore the following assertion fails:
https://github.com/PilzDE/pilz_robots/blob/430fecffbf372ff574a776f5150988556d54df0a/prbt_support/test/acceptance_tests/acceptance_test_joint_limits.py#L220

**Comment by martiniil** [comment]
Can be closed once #447 and #448 is merged.

**Comment by SansoneG** [comment]
Additions:

performed acceptance tests on commit 
7e593a1 and [0.5.18](https://github.com/PilzDE/pilz_robots/releases/tag/0.5.18)

__acceptance_test_joint_limits__
Failed with following output after executing ` rosrun prbt_support acceptance_test_joint_limits.py`:
```
Unknown attribute "name" in /robot[@name='prbt']/link[@name='prbt_link_2']/visual[1]
Perform joint_limit_overstepping_test for prbt_joint_1 [(y)es, (n)o]?: y


Start joint_limit_overstepping_test for prbt_joint_1

FUnknown attribute "name" in /robot[@name='prbt']/link[@name='prbt_link_2']/visual[1]
Perform joint_limit_reaching_test for prbt_joint_1 [(y)es, (n)o]?: y


Start joint_limit_reaching_test for prbt_joint_1

Perform joint_limit_reaching_test for prbt_joint_2 [(y)es, (n)o]?: n


Skip joint_limit_reaching_test for prbt_joint_2
___TEST-END___

Perform joint_limit_reaching_test for prbt_joint_3 [(y)es, (n)o]?: y


Start joint_limit_reaching_test for prbt_joint_3

Perform joint_limit_reaching_test for prbt_joint_4 [(y)es, (n)o]?: y


Start joint_limit_reaching_test for prbt_joint_4

Perform joint_limit_reaching_test for prbt_joint_6 [(y)es, (n)o]?: y


Start joint_limit_reaching_test for prbt_joint_6

.
======================================================================
FAIL: test_joint_limits_overstepping (__main__.AcceptanceTestJointLimits)
Perform all overstepping tests. Before each test ask the user if he wants to skip it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gsa/catkin_ws/src/pilz_robots/prbt_support/test/acceptance_tests/acceptance_test_joint_limits.py", line 245, in test_joint_limits_overstepping
    self._joint_limit_overstepping_test(name)
  File "/home/gsa/catkin_ws/src/pilz_robots/prbt_support/test/acceptance_tests/acceptance_test_joint_limits.py", line 220, in _joint_limit_overstepping_test
    self.assertFalse(self._execute_trajectory(lower_positions))
AssertionError: True is not false

----------------------------------------------------------------------
Ran 2 tests in 386.427s

FAILED (failures=1)
```


__acceptance_test_tcp__

Failed with following output after executing `roslaunch prbt_support test_urdf.launch`:
```
... logging to /home/gsa/.ros/log/febb3c02-e3b4-11ea-9b8c-64006a84e132/roslaunch-testzellecms-Precision-T1700-6690.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://testzellecms-Precision-T1700:41631/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_gui: True

NODES
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [6703]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to febb3c02-e3b4-11ea-9b8c-64006a84e132
process[rosout-1]: started with pid [6714]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [6717]
process[rviz-3]: started with pid [6722]
process[robot_state_publisher-4]: started with pid [6723]
[ WARN] [1598017710.502107407]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
[WARN] [1598017710.811919]: The 'use_gui' parameter was specified, which is deprecated.  We'll attempt to find and run the GUI, but if this fails you should install the 'joint_state_publisher_gui' package instead and run that.  This backwards compatibility option will be removed in Noetic.
[ERROR] [1598017710.812738]: Could not find the GUI, install the 'joint_state_publisher_gui' package
[joint_state_publisher-2] process has died [pid 6717, exit code 1, cmd /opt/ros/melodic/lib/joint_state_publisher/joint_state_publisher __name:=joint_state_publisher __log:=/home/gsa/.ros/log/febb3c02-e3b4-11ea-9b8c-64006a84e132/joint_state_publisher-2.log].
log file: /home/gsa/.ros/log/febb3c02-e3b4-11ea-9b8c-64006a84e132/joint_state_publisher-2*.log
```

screenshot:
![acceptance_test_tcp_failed](https://user-images.githubusercontent.com/50736605/90902032-231a9680-e3cc-11ea-8136-4edebde872e7.png)

**Comment by jschleicher** [comment]
Thank you for the report. Closing as #447 and #448 are merged now.
